(() => {
'use strict';
const key='openwheels-career-v1';let data=null;
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&Number.isInteger(saved.season)&&saved.season>0&&RaceRoster.validate(saved.grid)&&saved.performance&&Array.isArray(saved.history))data=saved;}catch(_){}
function performance(previous={}){return Object.fromEntries(RaceRoster.catalog.map(t=>{const old=previous[t.slug]||{speed:t.speed,acceleration:52};let delta=Math.floor(Math.random()*15)-7;if(!delta)delta=1;const speed=Math.max(298,Math.min(328,old.speed+delta));return[t.slug,{speed,acceleration:Math.round((47+Math.random()*11)*10)/10,previousSpeed:old.speed}];}));}
function persist(){localStorage.setItem(key,JSON.stringify(data));}
function apply(){RaceRoster.grid.splice(0,RaceRoster.grid.length,...data.grid.map(r=>({...r,pilots:[...r.pilots]})));RaceRoster.catalog.forEach(t=>{const p=data.performance[t.slug];if(p){t.speed=p.speed;t.acceleration=p.acceleration;}});}
if(!data){data={season:1,grid:RaceRoster.grid.map(r=>({...r,pilots:[...r.pilots]})),performance:performance(),history:[],changes:null};try{persist();}catch(_){}}
apply();
function podium(title,entries){const section=document.createElement('section');section.className='podium-group';const h=document.createElement('h3');h.textContent=title;section.append(h);const list=document.createElement('div');list.className='podium';entries.slice(0,3).forEach((entry,i)=>{const item=document.createElement('article');item.className=`podium-place place-${i+1}`;item.innerHTML=`<span class="medal">${['🥇','🥈','🥉'][i]}</span><img src="assets/teams/${entry.team}.svg" alt=""><strong></strong><small>${entry.points} PUAN</small>`;item.querySelector('strong').textContent=entry.name;list.append(item);});section.append(list);return section;}
function nextSeason(league){if(!league||league.results.length!==8||(league.season||1)!==data.season)return false;const teams=RaceLeague.table(true),drivers=RaceLeague.table();const relegated=teams.slice(-3).map(t=>t.id);const previousGrid=[...RaceRoster.grid];const reserves=RaceRoster.catalog.filter(t=>!previousGrid.some(r=>r.slug===t.slug));for(let i=reserves.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[reserves[i],reserves[j]]=[reserves[j],reserves[i]];}const promoted=reserves.slice(0,3);const grid=previousGrid.filter(t=>!relegated.includes(t.slug)).map(t=>({...t,pilots:[...t.pilots]}));const used=new Set(grid.flatMap(t=>t.pilots));for(const team of promoted){const candidates=[...team.drivers.map(d=>d[0]),...RaceRoster.drivers.map(d=>d.code)];const pilots=[];for(const code of candidates){if(!used.has(code)){pilots.push(code);used.add(code);}if(pilots.length===2)break;}grid.push({slug:team.slug,pilots});}if(!RaceRoster.validate(grid))throw Error('Yeni sezon kadrosu oluşturulamadı.');
const oldPlayer=league.drivers.find(d=>d.id===league.player);const retained=grid.find(r=>r.slug===oldPlayer?.team&&r.pilots.includes(oldPlayer.code));
const next={season:data.season+1,grid,performance:performance(data.performance),history:[...data.history,{season:data.season,drivers:drivers.slice(0,3),teams:teams.slice(0,3),relegated,promoted:promoted.map(t=>t.slug)}],preferredPlayer:retained?league.player:null,changes:{relegated,promoted:promoted.map(t=>t.slug),choosePilot:!retained}};
localStorage.setItem(key,JSON.stringify(next));data=next;apply();return true;}
function render(){const host=document.getElementById('career-panel');if(!host)return;host.replaceChildren();const end=RaceLeague.data?.results.length===8;if(end){const banner=document.createElement('div');banner.className='season-podium';banner.innerHTML=`<p class="podium-eyebrow">SEZON ${data.season} TAMAMLANDI</p>`;banner.append(podium('Pilotlar podyumu',RaceLeague.table()),podium('Takımlar podyumu',RaceLeague.table(true)));host.append(banner);const relegated=RaceLeague.table(true).slice(-3);const note=document.createElement('p');note.className='career-note';note.textContent='Yedeğe düşecek takımlar: '+relegated.map(t=>t.name).join(', ');host.append(note);}
if(data.changes){const note=document.createElement('p');note.className='career-note';const names=slugs=>slugs.map(s=>RaceRoster.catalog.find(t=>t.slug===s).name).join(', ');note.textContent=`Sezon ${data.season} · Gelenler: ${names(data.changes.promoted)}. Yedeğe düşenler: ${names(data.changes.relegated)}.${data.changes.choosePilot?' Önceki takımın/pilotun gridden ayrıldı; yeni pilotunu seç.':''}`;host.append(note);}
const detail=document.createElement('details');detail.className='performance-panel';detail.innerHTML=`<summary>Sezon ${data.season} · Takım performansları</summary><div class="performance-scroll"><table><thead><tr><th>Takım</th><th>Durum</th><th>Azami hız</th><th>Değişim</th><th>İvmelenme</th></tr></thead><tbody></tbody></table></div>`;RaceRoster.catalog.slice().sort((a,b)=>b.speed-a.speed).forEach(t=>{const p=data.performance[t.slug],delta=p.speed-p.previousSpeed,row=document.createElement('tr');row.innerHTML=`<td><img src="assets/teams/${t.slug}.svg" alt=""> <span></span></td><td>${RaceRoster.grid.some(r=>r.slug===t.slug)?'GRID':'YEDEK'}</td><td>${p.speed} km/sa</td><td class="${delta>=0?'gain':'loss'}">${delta>=0?'+':''}${delta}</td><td>${p.acceleration} km/sa/sn</td>`;row.querySelector('span').textContent=t.name;detail.querySelector('tbody').append(row);});host.append(detail);
if(data.history.length){const history=document.createElement('details');history.innerHTML='<summary>Geçmiş sezonlar</summary>';data.history.slice().reverse().forEach(s=>{const p=document.createElement('p');p.className='career-note';p.textContent=`Sezon ${s.season}: 🥇 ${s.drivers[0].name} · ${s.teams[0].name}`;history.append(p);});host.append(history);}}
window.RaceCareer={get data(){return data;},nextSeason,render,acceleration:slug=>data.performance[slug]?.acceleration||52,syncGrid(grid){const next={...data,grid:grid.map(r=>({...r,pilots:[...r.pilots]}))};localStorage.setItem(key,JSON.stringify(next));data=next;}};
})();